const  INCREMENT = "INCREMENT"
const DECREMENT = "DECREMENT"
const RESET = "RESET"
const INCREMENT_BY_VALUE = "INCREMENT_BY_VALUE"
const ADD_USER = "ADD_USER" 



module.exports ={
    INCREMENT,
    DECREMENT,
    RESET,
    INCREMENT_BY_VALUE,
    ADD_USER
}